INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('Salim ', '8 Rue Francis Carco, 75018, Paris', '48.889237', '2.356357', 'prive');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('Aura ', '1 Square de Clignqncourt, 75018, Paris', '48.892316', '2.345940', 'prive');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('David', '21 Boulevard de Rochechechouart, 75009, Paris', '48.883160', '2.346197', 'prive');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('Michel', '48 rue de Provence, 75009, 75009, Paris', '48.874397', '2.335515', 'prive');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('Sandrine', '13 Avenue de la Porte d'Italie, 75013, Paris', '48.817479', '2.360309', 'prive');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('Vincent', '4 rue des Panoyaux, 75020, Paris', '48.866228', '2.384704', 'prive');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('Laure', '42 Avenue des Gobellins, 75013, Paris', '48.835043', '2.353023', 'prive');
INSERT INTO `markers` (`name`, `address`, `lat`, `lng`, `type`) VALUES ('Tony', '66 Avenue du Maine, 75014, Paris', '48.839037', '2.321827', 'prive');